name: excel
description: A flutter and dart library for reading, creating, editing and updating excel sheets with compatible both on client and server side.
version: 4.0.6
homepage: https://github.com/justkawal/excel
topics:
  - excel
  - office
  - storage
  - sheets
  - spreadsheet

environment:
  sdk: ^3.8.0

dependencies:
  archive: ^4.0.5
  xml: ^6.5.0
  collection: ^1.19.1
  equatable: ^2.0.0

dev_dependencies:
  test: ^1.24.3
  lints: ^6.0.0

